# Generated by Django 2.2.4 on 2019-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antropometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(verbose_name=' рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name=' вес')),
                ('chest', models.PositiveSmallIntegerField(verbose_name=' окружность грудной клетки')),
                ('abdominal', models.PositiveSmallIntegerField(verbose_name=' окружность живота')),
                ('biceps', models.PositiveSmallIntegerField(verbose_name=' окружность бицепса')),
                ('thigh', models.PositiveSmallIntegerField(verbose_name=' окружность бедра')),
                ('shin', models.PositiveSmallIntegerField(verbose_name=' окружность голени')),
                ('add_datetime', models.DateTimeField(auto_now=True, verbose_name='время добавления данных')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='время посещения тренировки')),
                ('visit', models.BooleanField(default=False, verbose_name='пришел ли ты на тренировку')),
            ],
        ),
    ]
