# Generated by Django 2.2.4 on 2019-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antropometry',
            name='height',
        ),
        migrations.AddField(
            model_name='gallery',
            name='add_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='время добавления данных'),
        ),
    ]
