# Generated by Django 2.2.6 on 2019-11-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191024_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('add_datetime', models.DateTimeField(auto_now=True, verbose_name='время фото')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
