# Generated by Django 2.2.7 on 2019-11-09 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20191107_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometry',
            name='fitnessuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на тренирующегося'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='fitnessuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на тренирующегося'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='abdominal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' окружность живота'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='biceps',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' окружность бицепса'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='chest',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' окружность грудной клетки'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='shin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' окружность голени'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='thigh',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' окружность бедра'),
        ),
        migrations.AlterField(
            model_name='antropometry',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=' вес'),
        ),
    ]
