# Generated by Django 2.2.7 on 2019-11-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191110_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание тренировки')),
                ('short_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое описание тренировки')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Training', verbose_name='Ссылка на вид тренировки'),
        ),
    ]
