# Generated by Django 2.2.7 on 2019-11-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191110_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна ли тренировка'),
        ),
    ]
