# Generated by Django 2.2.7 on 2019-11-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='датавремя отправки сообщения'),
        ),
    ]
