# Generated by Django 2.2.4 on 2019-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatars'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
