# Generated by Django 2.2.4 on 2019-10-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191024_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='antropometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Antropometry'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Schedule'),
        ),
    ]
