# Generated by Django 2.2.7 on 2019-11-16 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20191109_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +999999999', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
