# Generated by Django 2.2.7 on 2019-11-27 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_fitnessuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +79998887766', regex='^\\+?7?\\d{10}$')]),
        ),
    ]
